---
# tasks file for idm-hostgroup
- name: Create hostsgroup for clients
  ipahostgroup:
    ipaadmin_password: "{{ admin_password }}"
    name: "{{ host_group }}"
    description: "Client servers"
    host:
    - rh8.web.example.com